/* (c) https://github.com/MontiCore/monticore */
plugins {
  id 'java-library'

  id "com.github.node-gradle.node" version "5.0.0"
  id 'de.rwth.se.umlp-tool-frontend' version "$mc_version"
}

node {
  download = true
  version = "${node_version}"
  nodeProxySettings = ProxySettings.OFF
  nodeProjectDir = file("${buildDir}/frontendGen")
}
nodeSetup.dependsOn(frontendSetup)

dependencies {
  //if(j2ts) {
  //  println("Hello WOrld!")
  //  domainSources project(":backend")
  //  implementation project(":backend")
  //}

  implementation group: "de.monticore.lang", name: 'guidsl', version: mc_version
  implementation group: "de.monticore.lang", name: 'guidsl', version: mc_version
}

genGUI {
  domainModels = ["VacuumGripperDashboard"]
  guiCreateModels = []
}

/*if(j2ts) {
  translateJava2TSDomain {
    domainModel = 'VacuumGripperDashboard'
    verbose = true
  }

  translateJava2TSGUI {
    domainModel = 'VacuumGripperDashboard'
    verbose = true
  }
}*/

task tmpCopyUmlpPackages(type: Copy){
  from("C:\\Users\\Hellwig\\projects\\umlp\\umlp-rte\\client\\build\\dist\\umlp\\mc\\fenix")
  into("$buildDir/frontendGen/node_modules/@umlp/")
}

nodeSetup.dependsOn(frontendSetup)

def prebuildTasks = [
    npmInstall, generate, tasks.tmpCopyUmlpPackages
]

task buildApp(type: NpxTask) {
  dependsOn(prebuildTasks)
  command = "ng"
  args = ["build"]
}
assemble.dependsOn(buildApp)

task testApp(type: NpxTask) {
  dependsOn(prebuildTasks)
  command = "ng"
  args = ["test"]
}

task run(type: NpxTask) {
  dependsOn(prebuildTasks)
  command = "ng"
  args = ["serve"]
}