plugins {
  id 'java'
  id("cd2pojo") version "$mc_version"
  id("montiarc-jsim") version "$mc_version"
}

group = 'de.se-rwth.fischertechnik'
version = "$mc_version"

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

repositories {
    maven {
        url = uri("https://nexus.se.rwth-aachen.de/content/groups/public/")
    }
    mavenCentral()
    maven { // Eclipse Paho
        url = "https://repo.eclipse.org/content/repositories/paho-releases/"
    }
}

dependencies {
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'

    implementation("montiarc.libraries:simulator-rte:$mc_version")
    // testImplementation "org.junit.jupiter:junit-jupiter:$junit_version"
    // testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: junit_version
    // testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: junit_version

    // testImplementation "montiarc.libraries:simulator-test-rte:$mc_version"
    testImplementation "org.assertj:assertj-core:3.24.2"
}

tasks.compileMontiarc {
  useClass2Mc.set(true)
}


test {
    useJUnitPlatform()
}