repo=https://nexus.se.rwth-aachen.de/content/groups/umlp

mavenUser=sle23_01
mavenPassword=n3VHkD5Mxc

mc_version=7.8.0-SNAPSHOT
spring_version=2.7.3
h2_database=2.1.214
spring_shell_version=2.1.8
node_version=18.13.0
playwright_version=1.44.0
jsweet_version=6.3.0

org.gradle.caching=false
# Can be enabled once Playwright tests are moved to Java
org.gradle.parallel=false

# Set to true to load dependencies and plugins from ~/.m2(or another repo if you changed it manually)
useLocalRepo=false
org.gradle.console=plain

version=7.8.0-SNAPSHOT

#ChangeMe
domainModel=FischertechnikVisualization
