plugins {
  id("java-library")
}

repositories {
  if (("true").equals(getProperty('useLocalRepo'))) {
    mavenLocal()
  }
  maven { // For MontiArc Plugins
    url = "https://nexus.se.rwth-aachen.de/content/groups/public/"
  }
  maven {
    credentials.username mavenUser
    credentials.password mavenPassword
    url "https://nexus.se.rwth-aachen.de/content/groups/monticore"
  }

  mavenCentral()
}

dependencies {
  implementation("de.monticore:monticore-runtime:7.8.0-SNAPSHOT")
  testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: junit_version
  testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: junit_version
}

test {
  useJUnitPlatform()
}

task jshell(type:Exec){
  def classpath = sourceSets.main.runtimeClasspath.filter { File f -> f.exists() }.asPath
  String startupScript = getProjectDir().toString() + "/Demo.jshell"
  commandLine("jshell", "--class-path", classpath, "--startup", startupScript)
  standardInput = System.in
  standardOutput = System.out
  errorOutput = System.err
  dependsOn(tasks.jar)
}

task printJshellCommand(){
  doFirst {
    def classpath = sourceSets.main.runtimeClasspath.filter { File f -> f.exists() }.asPath
    String startupScript = getProjectDir().toString() + "/Demo.jshell"
    print("jshell")
    print(" ")
    print("--class-path")
    print(" ")
    print("\"$classpath\"")
    print(" ")
    print("--startup")
    print(" ")
    println(startupScript)
  }
}