jdbc_driver=org.h2.Driver
database_url=jdbc:h2:mem:umlpdb
user=admin
password=docker

#Migration properties
#jdbc_driver=org.postgresql.Driver
#database_url=jdbc:postgresql://localhost:5432/umlpdb
#user=admin
#password=newpass
